# Generated by Django 4.2.16 on 2024-12-08 11:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_deliveryinfo_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'verbose_name_plural': 'Delivery Info'},
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(validators=[accounts.models.validate_16_digits])),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField(validators=[accounts.models.validate_3_or_4_digits])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Info',
            },
        ),
    ]
