# Generated by Django 4.2.16 on 2024-12-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deliveryinfo_options_paymentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
