# Generated by Django 4.2.16 on 2024-11-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
