# Generated by Django 4.2.16 on 2024-12-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'Checkouts'},
        ),
    ]
