# Generated by Django 4.2.16 on 2024-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('season', 'off by season'), ('off', 'only one left')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
