# Generated by Django 4.2.16 on 2024-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount_value',
        ),
    ]
