# Generated by Django 4.2.16 on 2025-01-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_checkout_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='products',
        ),
        migrations.AddField(
            model_name='orderline',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='shop.products'),
        ),
    ]
