# Generated by Django 4.2.16 on 2024-11-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategories',
            options={'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterModelOptions(
            name='posttags',
            options={'verbose_name_plural': 'Post Tags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
