# Generated by Django 4.2.16 on 2024-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0002_alter_post_options_alter_postcategories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
