# Generated by Django 4.2.16 on 2024-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0003_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
