# Generated by Django 4.2.16 on 2024-11-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0004_post_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pin',
        ),
    ]
